var BackendLink={
    login : "https://cyborg0.onrender.com/",
    reg   : "https://cyborg0.onrender.com/reg",
    jwt   : "https://cyborg0.onrender.com/jwt",
    data  : "https://cyborg0-1.onrender.com/data",
    market : "https://cyborg0.onrender.com/market",
    limit : "https://cyborg0.onrender.com/limit",
    deleteuser : "https://cyborg0.onrender.com/deleteuser",
    resetuser : "https://cyborg0.onrender.com/resetuser",
    addstocktowatchlist : "https://cyborg0.onrender.com/addstocktowatchlist",
    addwatchlist : "https://cyborg0.onrender.com/addwatchlist",
    deletewatchlist : "https://cyborg0.onrender.com/deletewatchlist",
    deletestock : "https://cyborg0.onrender.com/deletestock",
    portfolio : "https://cyborg0.onrender.com/portfolio",
    positions : "https://cyborg0.onrender.com/positions",
    orderHistory : "https://cyborg0.onrender.com/orderhistory",
    openorders : "https://cyborg0.onrender.com/openorders",
    account : "https://cyborg0.onrender.com/account",
    deliveryfetch : "https://cyborg0.onrender.com/deliveryfetch",
    intradayfetch : "https://cyborg0.onrender.com/intradayfetch",
    geneserve : "https://cyborg0-1.onrender.com/general",
    authserve : "https://cyborg0-1.onrender.com/auth",
};
export default BackendLink;

// var BackendLink={
//     login : "http://localhost:4000/",
//     reg   : "http://localhost:4000/reg",
//     jwt   : "http://localhost:4000/jwt",
//     data  : "http://localhost:4000/data",
//     market : "http://localhost:4000/market",
//     limit : "http://localhost:4000/limit",
//     deleteuser : "http://localhost:4000/deleteuser",
//     resetuser : "http://localhost:4000/resetuser",
//     addstocktowatchlist : "http://localhost:4000/addstocktowatchlist",
//     addwatchlist : "http://localhost:4000/addwatchlist",
//     deletewatchlist : "http://localhost:4000/deletewatchlist",
//     deletestock : "http://localhost:4000/deletestock",
//     portfolio : "http://localhost:4000/portfolio",
//     positions : "http://localhost:4000/positions",
//     orderHistory : "http://localhost:4000/orderhistory",
//     openorders : "http://localhost:4000/openorders",
//     account : "http://localhost:4000/account",
//     deliveryfetch : "http://localhost:4000/deliveryfetch",
//     intradayfetch : "http://localhost:4000/intradayfetch",
//     geneserve : "http://localhost:4002/general",
//     authserve : "http://localhost:4002/auth",
//     resetuser : "http://localhost:4000/resetuser",
//     deleteuser : "http://localhost:4000/deleteuser"
// };
// export default BackendLink;