var BackendLink={
    login : "http://localhost:4000/",
    reg   : "http://localhost:4000/reg",
    jwt   : "http://localhost:4000/jwt",
    data  : "http://localhost:4000/data",
    market : "http://localhost:4000/market",
    limit : "http://localhost:4000/limit",
    deleteuser : "http://localhost:4000/deleteuser",
    resetuser : "http://localhost:4000/resetuser",
    addstocktowatchlist : "http://localhost:4000/addstocktowatchlist",
    addwatchlist : "http://localhost:4000/addwatchlist",
    deletewatchlist : "http://localhost:4000/deletewatchlist",
    deletestock : "http://localhost:4000/deletestock",
    portfolio : "http://localhost:4000/portfolio",
    positions : "http://localhost:4000/positions",
    orderHistory : "http://localhost:4000/orderhistory",
    openorders : "http://localhost:4000/openorders",
    account : "http://localhost:4000/account",
    deliveryfetch : "http://localhost:4000/deliveryfetch",
    intradayfetch : "http://localhost:4000/intradayfetch",
    geneserve : "http://localhost:4002/general",
    authserve : "http://localhost:4002/auth",
    resetuser : "http://localhost:4000/resetuser",
    deleteuser : "http://localhost:4000/deleteuser"
};
export default BackendLink;